import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import ThemeToggle from '../components/ThemeToggle';
import { useTheme } from '../context/ThemeContext';
import { Bot, FlaskConical, BarChart, TrendingUp, FileText, Zap, GraduationCap, Clock, Check, BookOpen } from 'lucide-react';

const FEATURES = [
  { icon: <Bot />, title: 'AI Question Engine', desc: 'Every question is freshly generated by a local LLM — never repeated, always calibrated to difficulty.', accent: '#818cf8' },
  { icon: <FlaskConical />, title: 'Sandboxed Execution', desc: 'Code runs inside isolated Docker containers. 8 languages, strict resource limits, zero leakage.', accent: '#4ade80' },
  { icon: <BarChart />, title: 'Deep AI Review', desc: 'Beyond pass/fail — AI evaluates code quality, complexity, and delivers actionable improvement feedback.', accent: '#fbbf24' },
  { icon: <TrendingUp />, title: 'Live Analytics', desc: 'Track streaks, pass rates by difficulty, and score trends across your complete assessment history.', accent: '#38bdf8' },
  { icon: <FileText />, title: 'PDF Reports', desc: 'Download professional-grade PDF reports with full test breakdowns and AI feedback per submission.', accent: '#c084fc' },
  { icon: <Zap />, title: 'Built for Scale', desc: 'Designed for entire institutions running concurrent student assessments with zero performance drop.', accent: '#f87171' },
];

const STATS = [
  { value: '8+', label: 'Languages' },
  { value: '3', label: 'Difficulty Tiers' },
  { value: '∞', label: 'AI Questions' },
  { value: '100%', label: 'Open Source' },
];

const CODE_PREVIEW = `def two_sum(nums, target):
    seen = {}
    for i, num in enumerate(nums):
        complement = target - num
        if complement in seen:
            return [seen[complement], i]
        seen[num] = i`;

const stagger = { visible: { transition: { staggerChildren: 0.08 } } };
const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: [0.4, 0, 0.2, 1] } },
};

export default function Landing() {
  const navigate = useNavigate();
  const { isDark } = useTheme();

  return (
    <div style={{ minHeight: '100vh', overflowX: 'hidden', background: 'var(--bg-1)' }}>
      {/* Ambient gradient orbs */}
      <div style={{ position: 'fixed', inset: 0, pointerEvents: 'none', zIndex: 0, overflow: 'hidden' }}>
        <div style={{
          position: 'absolute', top: '-15%', left: '25%',
          width: '50vw', height: '50vw', borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(99,102,241,0.08) 0%, transparent 65%)',
        }} />
        <div style={{
          position: 'absolute', bottom: '5%', right: '-5%',
          width: '40vw', height: '40vw', borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(139,92,246,0.07) 0%, transparent 65%)',
        }} />
        <div style={{
          position: 'absolute', top: '40%', left: '-10%',
          width: '35vw', height: '35vw', borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(56,189,248,0.05) 0%, transparent 65%)',
        }} />
      </div>

      {/* Top Nav */}
      <nav style={{
        position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100,
        height: 56,
        background: isDark ? 'rgba(13,17,23,0.9)' : 'rgba(246,248,250,0.9)',
        backdropFilter: 'blur(20px)',
        borderBottom: '1px solid var(--border)',
        padding: '0 2rem',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <div style={{
            width: 28, height: 28, background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
            borderRadius: 7, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white',
            boxShadow: '0 4px 12px rgba(99,102,241,0.4)',
          }}><Zap size={16} /></div>
          <span style={{ fontFamily: "'Outfit', sans-serif", fontWeight: 800, fontSize: '0.95rem', color: 'var(--text-1)', letterSpacing: '-0.02em' }}>
            Code<span style={{ color: 'var(--accent)' }}>Go</span>
          </span>
        </div>
        <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
          <ThemeToggle />
          <button className="btn btn-ghost btn-sm" onClick={() => navigate('/login')}>Sign in</button>
          <button className="btn btn-primary btn-sm" onClick={() => navigate('/login')}>Get started →</button>
        </div>
      </nav>

      <div style={{ position: 'relative', zIndex: 1 }}>
        {/* HERO */}
        <section style={{
          minHeight: '100vh',
          display: 'flex', flexDirection: 'column',
          alignItems: 'center', justifyContent: 'center',
          textAlign: 'center',
          padding: '7rem 2rem 4rem',
        }}>
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
            <span style={{
              display: 'inline-flex', alignItems: 'center', gap: '0.4rem',
              padding: '0.3rem 0.875rem',
              background: isDark ? 'rgba(129,140,248,0.08)' : 'rgba(79,70,229,0.07)',
              border: '1px solid rgba(129,140,248,0.2)',
              borderRadius: 99,
              fontSize: '0.72rem', fontWeight: 700, color: 'var(--accent)',
              letterSpacing: '0.07em', textTransform: 'uppercase',
              marginBottom: '1.75rem', display: 'inline-flex',
            }}>
              <GraduationCap size={14} /> Institutional Coding Assessment Platform
            </span>
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.55, delay: 0.1 }}
            style={{
              fontFamily: "'Outfit', sans-serif",
              fontSize: 'clamp(2.5rem, 6vw, 4.5rem)',
              fontWeight: 900,
              letterSpacing: '-0.04em',
              lineHeight: 1.08,
              maxWidth: 860,
              marginBottom: '1.5rem',
            }}
          >
            Professional{' '}
            <span className="gradient-text">AI‑Powered</span>
            {' '}Coding Assessments
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            style={{
              fontSize: 'clamp(1rem, 2vw, 1.15rem)',
              color: 'var(--text-2)',
              maxWidth: 600, lineHeight: 1.75,
              marginBottom: '2.5rem',
            }}
          >
            AI generates unique questions, sandboxed containers execute code securely,
            and intelligent feedback helps students improve — all in one platform.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', justifyContent: 'center', marginBottom: '4rem' }}
          >
            <button className="btn btn-primary btn-lg" onClick={() => navigate('/login')}>
              Launch Platform →
            </button>
            <button className="btn btn-ghost btn-lg" onClick={() => navigate('/login')} style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <GraduationCap size={18} /> Try Student Demo
            </button>
          </motion.div>

          {/* Stats row */}
          <motion.div
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.45 }}
            style={{ display: 'flex', gap: '3rem', flexWrap: 'wrap', justifyContent: 'center', marginBottom: '5rem' }}
          >
            {STATS.map(s => (
              <div key={s.label} style={{ textAlign: 'center' }}>
                <div style={{
                  fontFamily: "'Outfit', sans-serif",
                  fontSize: '2rem', fontWeight: 900, letterSpacing: '-0.04em',
                  color: 'var(--accent)',
                }}>{s.value}</div>
                <div style={{ fontSize: '0.72rem', color: 'var(--text-3)', fontWeight: 600, letterSpacing: '0.07em', textTransform: 'uppercase' }}>
                  {s.label}
                </div>
              </div>
            ))}
          </motion.div>

          {/* IDE Preview Card */}
          <motion.div
            initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.5 }}
            style={{
              width: '100%', maxWidth: 920,
              background: 'var(--bg-2)',
              border: '1px solid var(--border)',
              borderRadius: 16,
              overflow: 'hidden',
              boxShadow: isDark
                ? '0 40px 100px rgba(0,0,0,0.7), 0 0 100px rgba(99,102,241,0.08)'
                : '0 20px 60px rgba(31,35,40,0.12)',
            }}
          >
            {/* IDE title bar */}
            <div className="ide-titlebar" style={{ padding: '0.6rem 1rem', justifyContent: 'space-between' }}>
              <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                <div className="ide-dot ide-dot-red" />
                <div className="ide-dot ide-dot-yellow" />
                <div className="ide-dot ide-dot-green" />
              </div>
              <div style={{
                flex: 1, maxWidth: 260, marginLeft: '0.75rem',
                background: 'var(--bg-3)', borderRadius: 6,
                padding: '0.25rem 0.75rem',
                fontSize: '0.72rem', color: 'var(--text-3)',
                textAlign: 'center',
              }}>
                codego.ai/assessment
              </div>
              <div style={{ display: 'flex', gap: 6 }}>
                <span className="badge badge-medium">INTERMEDIATE</span>
                <span style={{ fontSize: '0.72rem', color: 'var(--text-3)', alignSelf: 'center', display: 'flex', alignItems: 'center', gap: '0.2rem' }}><Clock size={12} /> 28:45</span>
              </div>
            </div>

            {/* Split editor view */}
            <div style={{ display: 'flex', height: 320 }}>
              {/* Problem panel */}
              <div style={{ width: '42%', padding: '1.25rem 1.5rem', borderRight: '1px solid var(--border)', overflowY: 'auto', background: 'var(--bg-card)' }}>
                <h3 style={{ fontSize: '0.95rem', marginBottom: '0.75rem' }}>Two Sum Problem</h3>
                <p style={{ fontSize: '0.8rem', lineHeight: 1.65, marginBottom: '1rem', color: 'var(--text-2)' }}>
                  Given an array of integers <code style={{ color: 'var(--accent)', fontFamily: 'JetBrains Mono, monospace', background: 'var(--accent-glow)', padding: '0 4px', borderRadius: 3 }}>nums</code> and an integer <code style={{ color: 'var(--accent)', fontFamily: 'JetBrains Mono, monospace', background: 'var(--accent-glow)', padding: '0 4px', borderRadius: 3 }}>target</code>, return indices of the two numbers that add up to target.
                </p>
                <div className="code-block" style={{ fontSize: '0.72rem' }}>
                  <span style={{ color: 'var(--text-3)' }}>Input: </span>
                  <span style={{ color: 'var(--neon-green)' }}>nums=[2,7,11,15], target=9</span>{'\n'}
                  <span style={{ color: 'var(--text-3)' }}>Output: </span>
                  <span style={{ color: 'var(--accent)' }}>[0, 1]</span>
                </div>
              </div>

              {/* Code editor panel */}
              <div style={{ flex: 1, background: isDark ? '#0d1117' : '#f6f8fa', padding: '1rem', overflow: 'hidden', fontFamily: 'JetBrains Mono, monospace', fontSize: '0.78rem', lineHeight: 1.8 }}>
                <div style={{ display: 'flex', marginBottom: 4 }}>
                  <span style={{ color: 'var(--text-3)', width: 20, textAlign: 'right', marginRight: 12, userSelect: 'none' }}>1</span>
                  <span><span style={{ color: '#ff7b72' }}>def </span><span style={{ color: '#d2a8ff' }}>two_sum</span><span style={{ color: 'var(--text-1)' }}>(nums, target):</span></span>
                </div>
                {[
                  [2, <><span style={{ color: '#79c0ff' }}>    seen</span> = {'{}'}</>],
                  [3, <><span style={{ color: '#ff7b72' }}>    for </span><span style={{ color: '#79c0ff' }}>i, num </span><span style={{ color: '#ff7b72' }}>in </span><span style={{ color: '#d2a8ff' }}>enumerate</span><span style={{ color: 'var(--text-1)' }}>(nums):</span></>],
                  [4, <><span style={{ color: '#79c0ff' }}>        complement</span> = target - num</>],
                  [5, <><span style={{ color: '#ff7b72' }}>        if </span>complement <span style={{ color: '#ff7b72' }}>in </span><span style={{ color: '#79c0ff' }}>seen</span>:</>],
                  [6, <><span style={{ color: '#ff7b72' }}>            return </span>[seen[complement], i]</>],
                  [7, <><span style={{ color: '#79c0ff' }}>        seen</span>[num] = i</>],
                ].map(([n, line]) => (
                  <div key={n as number} style={{ display: 'flex', marginBottom: 2 }}>
                    <span style={{ color: 'var(--text-3)', width: 20, textAlign: 'right', marginRight: 12, userSelect: 'none' }}>{n}</span>
                    <span style={{ color: 'var(--text-1)' }}>{line as React.ReactNode}</span>
                  </div>
                ))}
                <div style={{ marginTop: 12, display: 'inline-flex', alignItems: 'center', gap: 6, background: 'var(--green-bg)', border: '1px solid var(--green-border)', borderRadius: 6, padding: '0.3rem 0.75rem', fontSize: '0.72rem', color: 'var(--green)', fontFamily: 'Inter, sans-serif', fontWeight: 600 }}>
                  <Check size={14} /> All 5 test cases passed · Score 87/100
                </div>
              </div>
            </div>
          </motion.div>
        </section>

        {/* FEATURES */}
        <section style={{ padding: '5rem 2rem', maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
            <span style={{
              display: 'inline-block', padding: '0.25rem 0.75rem',
              background: 'var(--accent-glow)', border: '1px solid rgba(129,140,248,0.2)',
              borderRadius: 99, fontSize: '0.7rem', fontWeight: 700, color: 'var(--accent)',
              marginBottom: '1rem', letterSpacing: '0.07em', textTransform: 'uppercase',
            }}>Platform Features</span>
            <h2 style={{ fontFamily: "'Outfit', sans-serif", marginBottom: '0.875rem' }}>
              Everything you need, nothing you don't
            </h2>
            <p style={{ color: 'var(--text-2)', maxWidth: 480, margin: '0 auto', fontSize: '0.95rem' }}>
              Built for institutions. Designed to deliver fair, accurate, and scalable evaluations.
            </p>
          </div>

          <motion.div
            variants={stagger}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-50px' }}
            style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(290px, 1fr))', gap: '1rem' }}
          >
            {FEATURES.map(f => (
              <motion.div key={f.title} variants={fadeUp} className="card" style={{ borderTop: `2px solid ${f.accent}20` }}>
                <div style={{
                  width: 40, height: 40, borderRadius: 10,
                  background: f.accent + '14',
                  border: `1px solid ${f.accent}25`,
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: 18, marginBottom: '1rem',
                }}>
                  {f.icon}
                </div>
                <h3 style={{ fontSize: '0.95rem', marginBottom: '0.5rem', fontWeight: 600 }}>{f.title}</h3>
                <p style={{ fontSize: '0.85rem', lineHeight: 1.65 }}>{f.desc}</p>
              </motion.div>
            ))}
          </motion.div>
        </section>

        {/* CTA */}
        <section style={{ padding: '5rem 2rem', textAlign: 'center' }}>
          <motion.div
            initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            style={{
              maxWidth: 580, margin: '0 auto',
              background: isDark
                ? 'linear-gradient(135deg, rgba(99,102,241,0.08), rgba(139,92,246,0.06))'
                : 'linear-gradient(135deg, rgba(79,70,229,0.06), rgba(124,58,237,0.04))',
              border: '1px solid rgba(129,140,248,0.2)',
              borderRadius: 20, padding: '3rem 2.5rem',
            }}
          >
            <h2 style={{ fontFamily: "'Outfit', sans-serif", marginBottom: '0.875rem' }}>Ready to deploy?</h2>
            <p style={{ marginBottom: '2rem', color: 'var(--text-2)', fontSize: '0.95rem' }}>
              Empower your institution with next-generation AI coding assessments.
            </p>
            <div style={{ display: 'flex', gap: '0.75rem', justifyContent: 'center', flexWrap: 'wrap' }}>
              <button className="btn btn-primary btn-lg" onClick={() => navigate('/login')}>Start Now →</button>
              <button className="btn btn-ghost btn-lg" onClick={() => navigate('/login')} style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}><BookOpen size={18} /> View Demo</button>
            </div>
          </motion.div>
        </section>

        {/* Footer */}
        <footer style={{
          borderTop: '1px solid var(--border)',
          padding: '1.5rem 2rem',
          textAlign: 'center',
          color: 'var(--text-3)',
          fontSize: '0.8rem',
        }}>
          CodeGo — AI-Powered Institutional Assessment Platform · Open Source
        </footer>
      </div>
    </div>
  );
}
